### ISSUE TITLE
CSS Variables support for El?

### ISSUE THREAD

**Issue by TheHadiAhmadi** [yesvelte/yesvelte#215]
sometimes it would be useful if we can set css variables from `.svelte` files and use them in `.css` files. 

I know that we are not developing theme right now, but it would be good if this project can support css variables

```svelte
<Button color="red">
   red button
</Button>

<Button --color="#ff5000">
   #ff5000 button
</Button>
<!-- set --y-button-color property to #ff5000 -->

```

and in css file:
```css

.y-button {
    ....
    color: var(--y-button-color);
}

```
